"""empty message

Revision ID: 6aa501c61204
Revises: ab06097830f6
Create Date: 2022-11-01 16:20:08.832905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6aa501c61204'
down_revision = 'ab06097830f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('movie_cast', 'movie_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('movie_cast', 'actor_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_unique_constraint(None, 'movie_cast', ['movie_id', 'actor_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'movie_cast', type_='unique')
    op.alter_column('movie_cast', 'actor_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('movie_cast', 'movie_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
