"""empty message

Revision ID: ab06097830f6
Revises: 
Create Date: 2022-11-01 16:06:53.523834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab06097830f6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('movie_cast', 'movie_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('movie_cast', 'actor_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('movie_cast', 'actor_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('movie_cast', 'movie_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
